### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by darkowic** [englercj/resource-loader#84] opened 2017-01-20 08:57 UTC
This is connected with this webpack issue https://github.com/webpack/webpack/issues/4039

I use the resource-loader with pixi.js (error in version 4.3.4)

resource-loader 2.0.4
webpack 2.2.0

**Comment by englercj** [comment] 2017-01-20 17:36
Hmm, I assume this is because of this line?

https://github.com/englercj/resource-loader/blob/00a56a74c5f786351d5ced1f213460a88100ac47/src/index.js#L11

Do I need to just change the imports to be requires so my exports work correctly?

**Comment by darkowic** [comment] 2017-01-25 09:31
To be honest I don't know what is correct solution. Maybe in webpack issue will be more about it

**Comment by shijiansu** [comment] 2017-02-03 05:30
Hi guys,
I am a newbie in this area. I accidentally see this issue, and I also read the [webpack/webpack#4039](https://github.com/webpack/webpack/issues/4039). 
I faced the same error message though I am not using resource-loader. I hope here is some information may help, 

**The cause:**
According to johnwchadwick, it is,
> As it says, module.exports is read-only in ES modules. ... ...

**For temporary fix:** - For the people who faces the issue in their code.
I added below section into .babelrc, it works for me but may have some impact as mentioned by johnwchadwick. 
` "plugins": [
      "transform-es2015-modules-commonjs"
    ]`
Other transform-runtime plugin may work also but I am not using it.

**For Long term fix:**
As pointed out by @englercj, I think the resource-loader source code of <https://github.com/englercj/resource-loader/blob/00a56a74c5f786351d5ced1f213460a88100ac47/src/index.js#L11> may cause the issue. A way to solve it as according to johnwchadwick, it is,
> ... ... This can be fixed by simply replacing all module.exports = ... to export default ... where applicable, as this is seemingly equivalent for old Babel-style ES module transpilation. ... ...

My webpack version is as below,
"webpack": "2.2.1"

**Comment by englercj** [comment] 2017-02-24 17:21
Could you try this again using the `es6-webpack-fix` branch? I *might* have fixed it there, curious if it works for you.

**Comment by darkowic** [comment] 2017-02-24 20:43
Ok I can check it for you but on Monday. If I forgot please ping me :)

**Comment by englercj** [comment] 2017-03-03 04:59
@darkowic Ping! :D

**Comment by magnus-bergman** [comment] 2017-03-28 14:19
@englercj I can confirm that the issue is solved within the es6-webpack-fix branch.

**Comment by Syrou** [comment] 2017-05-15 16:10
Please let this go in :)

**Comment by englercj** [comment] 2017-05-17 17:10
Merged, I'll try to put a release out tonight.

**Closed** 2017-05-17 17:09 UTC
Labels: Bug

**Comment by englercj** [comment] 2017-05-18 13:27
`v2.0.8` has been released which should include the fix for this issue.
