### ISSUE TITLE
IE9 troubles

### ISSUE THREAD

**Issue by ex** [englercj/resource-loader#27] opened 2015-09-11 20:44 UTC
I'm using latest version on pixi.js 3.0.7 and I'm having random stalls on IE9.
Same code works fine on IE10. There are no error events fired.
The Readme here says IE9 is a TODO, but pixi guys says it's ok.
Is this a known issue?

**Comment by englercj** [comment] 2015-09-12 19:19
I am the pixi guy :) IE9 should work fine, the README is out of date. If you are having a problem, show me a running example of the error.

**Comment by Laurens-Bamtang** [comment] 2015-09-15 14:31
I'll try to get a sample of the error. Unfortunately this bug only shows up in a large project with lots of assets that are confidential, so its going to be kind of difficult for now. Actually, the problem didn't show when using few assets in the early stages of the project, so maybe this bug is related to the size/quantity of assets loaded. I tested regressing to latest pixi 2 version and the assets load fine so this is a v3 issue only.

**Comment by ex** [comment] 2015-09-15 14:34
I'll try to get a sample of the error. Unfortunately this bug only shows up in a large project with lots of assets that are confidential, so its going to be kind of difficult for now. Actually, the problem didn't show when using few assets in the early stages of the project, so maybe this bug is related to the size/quantity of assets loaded. I tested regressing to latest pixi 2 version and the assets load fine so this is a v3 issue only.

**Comment by englercj** [comment] 2016-07-28 16:11
Closing this since I never got a reproduction case.

**Closed by englercj** 2016-07-28 16:11 UTC
